services:
  sharelatex:
    image: sharelatex/sharelatex:latest
    container_name: sharelatex
    hostname: sharelatex
    env_file:
      - .env
    networks:
      overleaf_sharelatex:
        ipv4_address: ${APP_IP}
      mongodb: null
      overleaf_cache: null
    ports:
      - 80:80
    volumes:
      - ${APPSTORAGE}/sharelatex_data:/var/lib/overleaf
    stop_grace_period: 60s
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    env_file:
      - .env
    command: --replSet overleaf
    volumes:
      - ${DATABASE}/mongodb_data:/data/db
      - ${APPDATA}/server-ce/mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
    environment:
      MONGO_INITDB_DATABASE: ${OVERLEAF_INITDB_DATABASE}
    networks:
      - mongodb
    extra_hosts:
      # Required when using the automatic database setup for initializing the replica set.
      # This override is not needed when running the setup after starting up mongo.
      - mongo:127.0.0.1
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    labels:
      diun.enable: true
    restart: unless-stopped
  ################################################### valkey ###################################################
  # Valkey - Required for clustering and websocket support
  # Icon: https://cdn.jsdelivr.net/gh/loganmarchione/homelab-svg-assets//assets/valkey.svg
  # IP: 192.168.6.134
  valkey:
    image: valkey/valkey:8
    container_name: openwebui-valkey
    hostname: ${OPENWEBUI_VALKEY_HOST:-openwebui-valkey}
    env_file:
      - .env
    tmpfs:
      - /dev/shm:size=128m
    networks:
      - valkey
    ports:
      - 6379:6379
    volumes:
      - ${APPDATA}/broker:/data
    command: valkey-server --save 30 1 --loglevel warning
    labels:
      diun.enable: true
    restart: unless-stopped
networks:
  mongodb:
    internal: true
  valkey:
    internal: true
  sharelatex:
    driver: bridge